credentials:
  SLACK_BOT_TOKEN: ""
  SLACK_APP_TOKEN: ""
  SLACK_SIGNING_SECRET: 
  ED_APIS:
    {'cs-crossroads': "",
    'ee-crossroads': ""}
  ED_COURSE_IDS:
    {'cs-crossroads': ,
    'ee-crossroads': }

    
